name: DOC contributions to Ubuntu documentation
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint all files
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Check juju-tutorials
      uses: docker://avtodev/markdown-lint:v1
      with:
        config: './lint/config/tutorials.yml'
        args: >
          ./juju-tutorials/**.md
          ./samples/juju-tutorials-nextcloud-collabora.md
          ./templates/juju-tutorials.md

    - name: Check ubuntu-tutorials
      uses: docker://avtodev/markdown-lint:v1
      with:
        config: './lint/config/tutorials.yml'
        args: >
          ./ubuntu-tutorials/**.md
          ./samples/ubuntu-tutorials-howto-write-a-tutorial.md
          ./templates/ubuntu-tutorials.md

    # - name: Lint all files
    #   uses: docker://avtodev/markdown-lint:v1
    #   with:
    #     args: '.'
