name: DOC contributions to Ubuntu documentation
on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint all files
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint all files
      uses: docker://avtodev/markdown-lint:v1
      with:
        args: '.'
